import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProvider";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { SnigletFont } from "@/utils/customFont";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Pomodoro Task App",
  description: "Generated by daily web group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${SnigletFont.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('theme');
                const isDark = theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches);
                if (isDark) document.documentElement.classList.add('dark');
                else document.documentElement.classList.remove('dark');
              } catch(e) {}
            `,
          }}
        />
      </head>
      <body className="min-h-full flex bg-[#f4c1d4] flex-col">
        <ThemeProvider>
          <ReactQueryProvider>
            {children}

            <Toaster
              position="top-right"
              theme="system"
              toastOptions={{
                classNames: {
                  toast: `
                font-sniglet
                !rounded-[24px]
                !border
                !shadow-[0_12px_35px_rgba(0,0,0,.10)]
                !backdrop-blur-md

                !bg-white
                dark:!bg-[#31304A]

                !text-[#303153]
                dark:!text-white
              `,

                  title: `
                font-sniglet
                !font-semibold
                !text-[15px]

                !text-[#303153]
                dark:!text-white
              `,

                  description: `
                font-sniglet

                !text-[#7B7D93]
                dark:!text-[#C6C7D2]
              `,

                  success: `
                !border-[#59B7FF]/35

                !bg-gradient-to-r
                !from-[#EEF7FF]
                !to-[#F8FBFF]

                dark:!from-[#24374A]
                dark:!to-[#31304A]
              `,

                  error: `
                !border-[#FD81B0]/35

                !bg-gradient-to-r
                !from-[#FFF0F6]
                !to-[#FFF7FA]

                dark:!from-[#472A39]
                dark:!to-[#31304A]
              `,
                },
              }}
            />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
